-- Durable operations incidents, health scanning, and cleanup observability.

CREATE TABLE IF NOT EXISTS public.ops_incidents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint text NOT NULL,
  source text NOT NULL,
  event_code text NOT NULL,
  severity text NOT NULL,
  message text NOT NULL,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurrence_count integer NOT NULL DEFAULT 1,
  first_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  last_seen_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT ops_incidents_severity_check CHECK (severity IN ('info', 'warn', 'error', 'critical')),
  CONSTRAINT ops_incidents_occurrence_count_check CHECK (occurrence_count > 0),
  CONSTRAINT ops_incidents_fingerprint_check CHECK (char_length(fingerprint) BETWEEN 1 AND 500),
  CONSTRAINT ops_incidents_context_size_check CHECK (octet_length(context::text) <= 32768)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ops_incidents_open_fingerprint
  ON public.ops_incidents (fingerprint)
  WHERE resolved_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_ops_incidents_open_severity
  ON public.ops_incidents (severity, last_seen_at DESC)
  WHERE resolved_at IS NULL;

CREATE TABLE IF NOT EXISTS public.ops_health_checks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checked_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  result jsonb NOT NULL,
  CONSTRAINT ops_health_checks_result_size_check CHECK (octet_length(result::text) <= 32768)
);

CREATE INDEX IF NOT EXISTS idx_ops_health_checks_checked_at
  ON public.ops_health_checks (checked_at DESC);

ALTER TABLE public.ops_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_health_checks ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ops_incidents FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.ops_health_checks FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.ops_incidents_id_seq FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.ops_health_checks_id_seq FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.ops_incidents TO service_role;
GRANT ALL ON TABLE public.ops_health_checks TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ops_incidents_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ops_health_checks_id_seq TO service_role;

DROP POLICY IF EXISTS "ops incidents: service role only" ON public.ops_incidents;
CREATE POLICY "ops incidents: service role only"
  ON public.ops_incidents FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "ops health checks: service role only" ON public.ops_health_checks;
CREATE POLICY "ops health checks: service role only"
  ON public.ops_health_checks FOR ALL TO service_role
  USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.record_ops_incident(
  p_fingerprint text,
  p_source text,
  p_event_code text,
  p_severity text,
  p_message text,
  p_context jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_id bigint;
  v_occurrence_count integer;
  v_fingerprint text := left(btrim(COALESCE(p_fingerprint, '')), 500);
  v_context jsonb := COALESCE(p_context, '{}'::jsonb);
BEGIN
  IF v_fingerprint = '' THEN
    RAISE EXCEPTION 'INVALID_INCIDENT_FINGERPRINT' USING ERRCODE = '22023';
  END IF;
  IF p_severity NOT IN ('info', 'warn', 'error', 'critical') THEN
    RAISE EXCEPTION 'INVALID_INCIDENT_SEVERITY' USING ERRCODE = '22023';
  END IF;
  IF p_source IS NULL OR btrim(p_source) = '' OR char_length(p_source) > 120 THEN
    RAISE EXCEPTION 'INVALID_INCIDENT_SOURCE' USING ERRCODE = '22023';
  END IF;
  IF p_event_code IS NULL OR btrim(p_event_code) = '' OR char_length(p_event_code) > 160 THEN
    RAISE EXCEPTION 'INVALID_INCIDENT_EVENT_CODE' USING ERRCODE = '22023';
  END IF;
  IF p_message IS NULL OR btrim(p_message) = '' THEN
    RAISE EXCEPTION 'INVALID_INCIDENT_MESSAGE' USING ERRCODE = '22023';
  END IF;
  IF octet_length(v_context::text) > 32768 THEN
    RAISE EXCEPTION 'INCIDENT_CONTEXT_TOO_LARGE' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.ops_incidents (
    fingerprint, source, event_code, severity, message, context
  )
  VALUES (
    v_fingerprint,
    left(p_source, 120),
    left(p_event_code, 160),
    p_severity,
    left(p_message, 4000),
    v_context
  )
  ON CONFLICT (fingerprint) WHERE resolved_at IS NULL
  DO UPDATE SET
    severity = EXCLUDED.severity,
    message = EXCLUDED.message,
    context = public.ops_incidents.context || EXCLUDED.context,
    occurrence_count = public.ops_incidents.occurrence_count + 1,
    last_seen_at = clock_timestamp()
  RETURNING id, occurrence_count INTO v_id, v_occurrence_count;

  RETURN jsonb_build_object('id', v_id, 'occurrenceCount', v_occurrence_count);
END;
$function$;

CREATE OR REPLACE FUNCTION public.scan_ops_health()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_pending integer;
  v_processing integer;
  v_refund_missing integer;
  v_storyboard_cleanup_overdue integer;
  v_reference_cleanup_overdue integer;
  v_result jsonb;
BEGIN
  SELECT count(*) INTO v_pending
  FROM public.storyboards
  WHERE status = 'pending'
    AND deleted_at IS NULL
    AND next_attempt_at < now() - interval '10 minutes';

  SELECT count(*) INTO v_processing
  FROM public.storyboards
  WHERE status = 'processing'
    AND deleted_at IS NULL
    AND lease_expires_at < now() - interval '5 minutes';

  SELECT count(*) INTO v_refund_missing
  FROM public.storyboards
  WHERE status = 'failed'
    AND deleted_at IS NULL
    AND credit_charged_at IS NOT NULL
    AND credit_refunded_at IS NULL
    AND updated_at < now() - interval '2 minutes';

  SELECT count(*) INTO v_storyboard_cleanup_overdue
  FROM public.storyboards
  WHERE status IN ('completed', 'failed')
    AND deleted_at IS NULL
    AND expires_at < now() - interval '36 hours';

  SELECT count(*) INTO v_reference_cleanup_overdue
  FROM public.reference_images
  WHERE expires_at < now() - interval '36 hours';

  IF v_pending > 0 THEN
    PERFORM public.record_ops_incident(
      'health:STORYBOARD_PENDING_STUCK', 'database-health-scan',
      'STORYBOARD_PENDING_STUCK', 'critical',
      v_pending || ' Storyboard job(s) have been ready for more than 10 minutes',
      jsonb_build_object('count', v_pending)
    );
  ELSE
    UPDATE public.ops_incidents SET resolved_at = clock_timestamp(), last_seen_at = clock_timestamp()
    WHERE fingerprint = 'health:STORYBOARD_PENDING_STUCK' AND resolved_at IS NULL;
  END IF;

  IF v_processing > 0 THEN
    PERFORM public.record_ops_incident(
      'health:STORYBOARD_PROCESSING_STUCK', 'database-health-scan',
      'STORYBOARD_PROCESSING_STUCK', 'critical',
      v_processing || ' Storyboard lease(s) have been expired for more than 5 minutes',
      jsonb_build_object('count', v_processing)
    );
  ELSE
    UPDATE public.ops_incidents SET resolved_at = clock_timestamp(), last_seen_at = clock_timestamp()
    WHERE fingerprint = 'health:STORYBOARD_PROCESSING_STUCK' AND resolved_at IS NULL;
  END IF;

  IF v_refund_missing > 0 THEN
    PERFORM public.record_ops_incident(
      'health:STORYBOARD_REFUND_MISSING', 'database-health-scan',
      'STORYBOARD_REFUND_MISSING', 'critical',
      v_refund_missing || ' failed paid Storyboard job(s) are missing refunds',
      jsonb_build_object('count', v_refund_missing)
    );
  ELSE
    UPDATE public.ops_incidents SET resolved_at = clock_timestamp(), last_seen_at = clock_timestamp()
    WHERE fingerprint = 'health:STORYBOARD_REFUND_MISSING' AND resolved_at IS NULL;
  END IF;

  IF v_storyboard_cleanup_overdue > 0 OR v_reference_cleanup_overdue > 0 THEN
    PERFORM public.record_ops_incident(
      'health:CLEANUP_OVERDUE', 'database-health-scan',
      'CLEANUP_OVERDUE', 'error',
      'Expired Storage-backed records remain overdue for cleanup',
      jsonb_build_object(
        'storyboards', v_storyboard_cleanup_overdue,
        'referenceImages', v_reference_cleanup_overdue
      )
    );
  ELSE
    UPDATE public.ops_incidents SET resolved_at = clock_timestamp(), last_seen_at = clock_timestamp()
    WHERE fingerprint = 'health:CLEANUP_OVERDUE' AND resolved_at IS NULL;
  END IF;

  v_result := jsonb_build_object(
    'pendingStuck', v_pending,
    'processingStuck', v_processing,
    'refundMissing', v_refund_missing,
    'storyboardCleanupOverdue', v_storyboard_cleanup_overdue,
    'referenceCleanupOverdue', v_reference_cleanup_overdue
  );

  INSERT INTO public.ops_health_checks (result) VALUES (v_result);
  DELETE FROM public.ops_health_checks WHERE checked_at < now() - interval '30 days';

  RETURN v_result;
END;
$function$;

REVOKE ALL ON FUNCTION public.record_ops_incident(text, text, text, text, text, jsonb)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.scan_ops_health()
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.record_ops_incident(text, text, text, text, text, jsonb)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.scan_ops_health()
  TO service_role;

CREATE INDEX IF NOT EXISTS idx_usage_logs_user_id ON public.usage_logs (user_id);

CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;

DO $schedule$
DECLARE
  v_job record;
BEGIN
  FOR v_job IN
    SELECT jobid FROM cron.job WHERE jobname = 'promptgen-ops-health-scan'
  LOOP
    PERFORM cron.unschedule(v_job.jobid);
  END LOOP;

  PERFORM cron.schedule(
    'promptgen-ops-health-scan',
    '*/5 * * * *',
    $command$SELECT public.scan_ops_health();$command$
  );
END;
$schedule$;
